# fly.toml app configuration file generated for coloso-node on 2023-06-16T17:32:41+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coloso-node"
primary_region = "waw"

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0

[[mounts]]
  destination = "/volume"
  source = "coloso_data"
